### ISSUE TITLE
This page could not be found.

### ISSUE THREAD

**Issue by rohmanhm** [styled-components/colors-demo#2]
Hi. I can't open your demo URL https://www.styled-components.com/color-schemer/

**Comment by benevolentprof** [comment]
I'm having the same problem.

**Comment by stevemao** [comment]
@mxstbr How can we fix this?

**Comment by mxstbr** [comment]
I'm on it, sorry about that!

**Comment by mxstbr** [comment]
Here you go, sorry about that! https://colors.styled-components.com
